on:
  schedule:
    - cron: '39 5 * * *' # 每天午夜执行，你可以根据需要修改时间

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork repository
        run: |
          git clone https://github.com/smx1111/Live my_fork
          cd my_fork
          git remote add upstream https://github.com/YueChan/Live.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin master
