on:
  schedule:
    - cron: '24 7 * * *' # 每天午夜执行，你可以根据需要修改时间

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork repository
        run: |
          git clone https://github.com/smx1111/Live my_fork
          cd my_fork

      - name: Configure upstream
        run: |
          git remote add upstream <upstream_repository> # 上游仓库的 URL
          git fetch upstream

      - name: Merge changes from upstream
        run: |
          git checkout master
          git merge upstream/master
          git push origin master
