on:
  schedule:
    - cron: '42 5 * * *' # 每天午夜执行，你可以根据需要修改时间

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork repository
        run: |
          git clone https://github.com/smx1111/Live.git my_fork
          cd my_fork

      - name: Configure upstream
        run: |
          curl "https://www.google.com"
